AlexKomaha/Chrysalis

Procfile
app/controllers/emotions_controller.rb
app/controllers/journals_controller.rb
app/controllers/user_controller.rb
app/controllers/user_goals_controller.rb
test/controllers/app/controllers/user_goals_controller.rb_controller_test.rb
test/controllers/controllers/user_goals_controller.rb_controller_test.rb

controllers

---

config/environments/production.rb

Uncommented a line in file to allow for automatic redirection from http:// URLs to https:// (using a 301 and preserving the path).

Force SSL in rails

---

app/controllers/journals_controller.rb
app/controllers/user_controller.rb
app/controllers/users_controller.rb
app/policies/users_policy.rb
app/views/users/dashboard.html.erb
config/routes.rb

Added dashboard controller at users_controller / policy / dashboard

added dashboard

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_progress.scss
app/assets/stylesheets/components/_user_goals_index.scss
app/controllers/user_goals_controller.rb
app/views/user_goals/index.html.erb

Added progress bars and edited the style of the index page.

Index user goals

---

app/assets/stylesheets/pages/_journal.scss
app/controllers/journals_controller.rb
app/policies/application_policy.rb
app/views/journals/index.html.erb
app/views/journals/show.html.erb

Added the journal show page

---

app/controllers/user_goals_controller.rb
app/views/user_goals/index.html.erb
db/seeds.rb

Now the progress bars show how many times a user have accomplished their goals and change its width.
Empty bars are when a user choose a goal but didn't accomplish on the day. The bar wil change when they choose the same goal on another day and accomplish.

Progress bars

---

app/assets/stylesheets/components/_user_goals_index.scss
app/controllers/user_goals_controller.rb
app/views/user_goals/index.html.erb

Change the bars' colour to pastel we might use for the entier app.

Change each bars' colour

---

app/assets/stylesheets/components/_button.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/user_goals/new.html.erb

Edited buttons

---

db/seeds.rb

Added some more realistic seeds

---

app/assets/stylesheets/components/_navbar.scss

Managed to change the dropdown items colour when you click.
I just now set them lightgrey, but if you have any suggestion for the colour, please let me know then I will change it.

Changed the color when you click

---

app/controllers/users_controller.rb
app/views/users/_goals_achieved.html.erb

Change the bars colour matching to the progress page and change the text colour to black.

Dashboard bars

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/_how.html.erb
app/views/pages/_review_cards.html.erb
app/views/pages/home.html.erb

Added details

---

app/assets/stylesheets/components/_user_goals_index.scss
app/views/user_goals/index.html.erb

Added a star icon and some mergin-bottom on the bars.
Also made texts bold.

Style up indexpage

---

app/views/user_goals/index.html.erb

Added the check icon next to the header

---

app/assets/stylesheets/components/_checkbox.scss
app/controllers/user_goals_controller.rb
app/views/pages/home.html.erb
app/views/users/_checkbox.html.erb
app/views/users/_goal_cards.html.erb
app/views/users/dashboard.html.erb

Checkboxes

---

app/policies/journal_policy.rb
app/views/journals/index.html.erb
app/views/journals/show.html.erb
db/seeds.rb

-Now you can see several journals and also add new journals.
-Added date on journal index page and show page and it shows today date as we created the journals today. So might need to add several different dates.
-Changed the style of the title and date. Now titles and dates are at both ends.
Still need more works on styling

Journal seed

---

app/views/journals/index.html.erb

Added truncate

---

app/assets/stylesheets/components/_button.scss
app/views/emotions/index.html.erb

Styling for the top of the emotions index page

---

app/controllers/journals_controller.rb
db/seeds.rb

Now all dates are different dates.

Journals date

---

app/assets/stylesheets/components/_calendar.scss
app/views/simple_calendar/_month_calendar.html.erb

Added the design to the calendar

---

app/controllers/users_controller.rb
app/views/users/_emotions_calendar.html.erb
app/views/users/dashboard.html.erb

Added the emotion calendar on the dashboard.

Added the emotions calender on the dashboard

---

app/assets/stylesheets/components/_calendar.scss
app/assets/stylesheets/config/_colors.scss
app/views/emotions/index.html.erb
app/views/simple_calendar/_month_calendar.html.erb
db/seeds.rb

Calendar css

---

db/seeds.rb

Edited seeds for emotions

---

app/views/emotions/index.html.erb

icons at emotions

---

app/controllers/journals_controller.rb

Fix the data bug we had and changed the date ordered by asc.

Fixed the date bug and changed order by asc

---

app/controllers/journals_controller.rb
app/views/journals/show.html.erb

Added the emotions color on the journals as a background

Emotions Color at Journals

---

public/404.html
public/500.html

Can check on links below:
http://localhost:3000/404.html
http://localhost:3000/500.html

Added custom error pages for 404 and 500

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_cards.scss
app/controllers/users_controller.rb
app/views/users/dashboard.html.erb

Journal on dash

---

app/assets/stylesheets/components/_cards.scss
app/views/users/dashboard.html.erb

journal button color and style

---

app/assets/stylesheets/components/_cards.scss
app/views/pages/home.html.erb

Edited quote card on landing

---

app/assets/stylesheets/pages/_journal.scss
app/views/articles/index.html.erb
app/views/journals/show.html.erb

Article icon

---

app/assets/stylesheets/components/_cards.scss
app/views/articles/index.html.erb

Not complete but just made the cards

Articles page

---

app/assets/stylesheets/components/_button.scss
app/views/users/dashboard.html.erb

Dashboard icon

---

app/assets/stylesheets/components/_calendar.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_dashboard.scss
app/controllers/users_controller.rb
app/views/users/_goal_cards.html.erb
app/views/users/_recent.html.erb
app/views/users/dashboard.html.erb

Edited dashboard so there is a sneak peek of the bottom two cards

Edit dashboard

---

db/seeds.rb

Added a user for 'Ayumi' for demo day

Added demo day user

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_footer.scss

- Changed colour of the links to the websites on the resources page. 
- Fixed footer to the bottom of the page.

Footer fixed to the bottom

---

app/controllers/journals_controller.rb
app/models/journal.rb
app/views/journals/edit.html.erb
app/views/journals/new.html.erb
app/views/journals/show.html.erb

Edit function
